Repository culturespot/CultureSpot-Frontend, pull requests merged in 2025-04, with the labels that each got.

#21 [feat] CUL-180: Carousel 컴포넌트 개발
  app/(main-layout)/page.tsx
  package-lock.json
  package.json
  src/components/Common/Carousel.tsx
  src/components/Common/EventCarousel.tsx
  src/components/Common/NavigationBar.tsx
  src/components/common/Card.tsx
  src/components/common/ContentCard.tsx
  src/components/common/Header.tsx
  src/data/mockEvent.ts
  src/utils/formatDuration.ts
Labels: feature

#23 [feat] CUL-113: 홈 화면 개발(`MainCarousel`, `EventCarousel`) 및 `GenreButton` 삭제 (`ToggleButton`, `RemovableButton`으로 분리)
  app/(main-layout)/my/profile/page.tsx
  app/(main-layout)/page.tsx
  app/(main-layout)/search/page.tsx
  package-lock.json
  package.json
  src/components/Common/EventCarousel.tsx
  src/components/Common/MainCarousel.tsx
  src/components/Common/RemovableButton.tsx
  src/components/Common/ToggleButton.tsx
  src/components/common/ContentCard.tsx
  src/components/common/GenreButton.tsx
  src/components/common/Header.tsx
  src/constants/event.ts
  src/data/mockAdvertisement.ts
  src/types/advertisement.ts
  src/types/event.ts
Labels: enhancement, feature

#25 [feat] CUL-194: 세션 만료 시 전역 상태 기반 toast 알림 및 로그인 리다이렉트 처리
  app/(main-layout)/layout.tsx
  package-lock.json
  package.json
  src/api/responseInterceptor.ts
  src/components/system/SessionEffect.tsx
  src/stores/sessionStore.ts
Labels: enhancement, refactor

#27 [refactor] CUL-197: 홈 화면 및 내비게이션바 UI 개선
  app/(main-layout)/page.tsx
  src/components/Common/navbar/SidebarContent.tsx
  src/components/common/ContentCard.tsx
  src/components/common/SearchBar.tsx
  src/components/common/carousel/EventCarousel.tsx
  src/components/common/navbar/Header.tsx
  src/components/common/navbar/NavigationBar.tsx
  src/components/common/navbar/Sidebar.tsx
  src/constants/sidebarItems.ts
  src/data/mockEvent.ts
  src/icons/iconsPaths.ts
Labels: refactor

#28 [fix] CUL-191: Build 에러 해결(`common` 폴더의 casing 문제)
  src/components/Common/ActionBar.tsx
  src/components/Common/AvatarProfile.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/ListToolbar.tsx
  src/components/Common/LogoAnimation.tsx
  src/components/Common/Textarea.tsx
  src/components/common/navbar/SidebarContent.tsx
Labels: bug

#29 [feat] CUL 201: Header 로고 애니메이션 개발
  app/(auth-layout)/layout.tsx
  public/assets/title.svg
  src/components/common/HeaderLogo.tsx
  src/components/common/LogoAnimation.tsx
  src/components/common/navbar/Header.tsx
  src/components/system/RotatingLogo.tsx
Labels: feature, refactor

#30 [fix] CUL-200: 프로필 수정 페이지 및 버튼 UI 피드백 반영
  app/(main-layout)/my/profile/page.tsx
  src/components/common/Input.tsx
  src/components/common/button/Button.tsx
Labels: fix

#31 [feat] CUL-195: Footer 컴포넌트 개발
  app/(main-layout)/page.tsx
  package-lock.json
  package.json
  src/components/common/Footer.tsx
  src/components/common/navbar/NavigationBar.tsx
Labels: feature

#32 [feat] CUL-118: 공연/전시 추천 페이지 UI 개발
  app/(main-layout)/events/[id]/page.tsx
  app/(main-layout)/exhibition/page.tsx
  app/(main-layout)/my/profile/page.tsx
  app/(main-layout)/page.tsx
  app/(main-layout)/performance/page.tsx
  app/(main-layout)/search/page.tsx
  public/assets/genre/genre-architecture.svg
  public/assets/genre/genre-cultural-policy.svg
  public/assets/genre/genre-dance.svg
  public/assets/genre/genre-exhibition.svg
  public/assets/genre/genre-festival.svg
  public/assets/genre/genre-fine-arts.svg
  public/assets/genre/genre-literature.svg
  public/assets/genre/genre-music.svg
  public/assets/genre/genre-others.svg
  public/assets/genre/genre-theater.svg
  public/assets/genre/genre-visual-media.svg
  src/components/common/button/GenreSearchButton.tsx
  src/components/common/carousel/EventCarousel.tsx
  src/components/page/events/EventSection.tsx
  src/constants/event.ts
  src/icons/Icon.tsx
  src/types/event.ts
  src/utils/createMapping.ts
  src/utils/toKebabCase.ts
Labels: feature, refactor

#33 [refactor] CUL-226: 기존 컴포넌트 및 페이지 코드 리팩토링
  app/(auth-layout)/layout.tsx
  app/(auth-layout)/login/page.tsx
  app/(main-layout)/my/profile/page.tsx
  public/assets/logos/logo-icon.svg
  public/assets/logos/logo.svg
  public/assets/logos/title.svg
  public/assets/ui/ticketbook-qr-code.png
  src/components/common/AvatarProfile.tsx
  src/components/common/ContentCard.tsx
  src/components/common/Footer.tsx
  src/components/common/HeaderLogo.tsx
  src/components/common/Input.tsx
  src/components/common/SearchBar.tsx
  src/components/page/ticketbook/TicketbookDetail.tsx
  src/components/system/RotatingLogo.tsx
Labels: feature, refactor

#34 [fix] CUL-254: 구글/카카오 소셜 로그인 버튼을 회사의 디자인 가이드에 맞게 업데이트
  app/(auth-layout)/login/page.tsx
  public/assets/ui/kakao_login.svg
  src/components/common/button/Button.tsx
  src/components/common/button/GoogleLoginButton.tsx
Labels: refactor, fix

#35 [feat] CUL-266: Scroll-to-top 버튼 개발
  app/(main-layout)/layout.tsx
  src/components/common/ScrollToTop.tsx
Labels: feature
