Repository culturespot/CultureSpot-Frontend, pull requests merged in 2025-03, with the labels that each got.

#5 [feat] Dropdown 컴포넌트 구현
  src/components/Common/Dropdown.tsx
  src/constants/iconsPaths.ts
Labels: feature

#6 [feat] Sidebar 컴포넌트 구현
  app/layout.tsx
  src/components/Common/Sidebar.tsx
  src/constants/sidebarItems.ts
Labels: feature

#7 [feat] 공통 컴포넌트 개발
  package-lock.json
  package.json
  public/assets/Logo Icon.svg
  public/assets/Logo.svg
  src/components/common/Button.tsx
  src/components/common/Card.tsx
  src/components/common/ContentCard.tsx
  src/components/common/GenreButton.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/LikeButton.tsx
  src/components/common/SearchBar.tsx
  src/components/init.md
  src/components/modal/CommonDialog.tsx
  src/components/modal/CommonModal.tsx
  src/components/modal/ContentDialog.tsx
  src/components/modal/ContentModal.tsx
  src/components/page/init.md
  tailwind.config.js
Labels: feature

#11 [feat] auth-layout 개발
  app/(auth-layout)/layout.tsx
  app/(auth-layout)/login/page.tsx
  package-lock.json
  package.json
  src/components/Common/LogoAnimation.tsx
Labels: feature

#14 [feat] CUL-116 공통 컴포넌트 수정 및 개발
  app/(auth-layout)/layout.tsx
  app/(auth-layout)/login/page.tsx
  src/components/Common/ActionBar.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/ListToolbar.tsx
  src/components/common/Header.tsx
Labels: feature

#15 [feat] CUL-116 공통 컴포넌트 수정 및 개발 (추가 작업)
  src/components/Common/Dropdown.tsx
  src/components/Common/EditDeleteButton.tsx
  src/components/Common/ListToolbar.tsx
  src/components/Common/NavigationBar.tsx
  src/components/Common/SidebarProfile.tsx
  src/components/Common/Textarea.tsx
  src/components/common/Header.tsx
  src/data/mockUser.ts
  src/types/init.md
  src/types/user.ts
Labels: feature

#17 [fix] CUL-159: 절대경로 사용 및 스타일 옵션 수정
  app/(auth-layout)/layout.tsx
  app/(auth-layout)/login/page.tsx
  app/(main-layout)/layout.tsx
  app/(main-layout)/my/profile/page.tsx
  src/components/Common/ActionBar.tsx
  src/components/Common/AvatarProfile.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/ListToolbar.tsx
  src/components/Common/NavigationBar.tsx
  src/components/Common/Sidebar.tsx
  src/components/Common/SidebarProfile.tsx
  src/components/Common/Textarea.tsx
  src/components/common/Card.tsx
  src/components/common/ContentCard.tsx
  src/components/common/GenreButton.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/LikeButton.tsx
  src/components/common/SearchBar.tsx
  src/components/modal/CommonDialog.tsx
  src/components/modal/ContentDialog.tsx
  src/components/modal/ModalContainer.tsx
  src/components/page/community/CommentEditForm.tsx
  src/components/page/community/CommentListItem.tsx
  src/components/page/community/CommentListToolbar.tsx
  src/components/page/community/CommentPostForm.tsx
  src/components/page/community/PostListItem.tsx
  src/components/page/community/PostListToolbar.tsx
  src/styles/globals.css
  tailwind.config.js
  tsconfig.json
Labels: refactor

#18 [feat] CUL-156: 티켓북, 알림 컴포넌트 개발
  eslint.config.js
  public/assets/ticketbook-qr-code.png
  src/components/common/Header.tsx
  src/components/page/notification/NotificationHeader.tsx
  src/components/page/notification/NotificationListItem.tsx
  src/components/page/notification/NotificationListToolbar.tsx
  src/components/page/notification/NotificationPopup.tsx
  src/components/page/ticketbook/Rating.tsx
  src/components/page/ticketbook/TicketbookDetail.module.css
  src/components/page/ticketbook/TicketbookDetail.tsx
  src/data/mockEvent.ts
  src/data/mockNotification.ts
  src/data/mockTicketbook.ts
  src/types/event.ts
  src/types/notification.ts
  src/types/ticketbook.ts
Labels: feature

#19 [feat] CUL-177: SearchBar 컴포넌트 스타일 variants 추가
  src/components/common/SearchBar.tsx
Labels: enhancement

#20 [refactor] code convention에 따른 코드 스타일 변경
  app/(auth-layout)/layout.tsx
  app/(auth-layout)/login/page.tsx
  app/(main-layout)/community/page.tsx
  app/(main-layout)/exhibition/page.tsx
  app/(main-layout)/layout.tsx
  app/(main-layout)/my/dashboard/page.tsx
  app/(main-layout)/my/likes/page.tsx
  app/(main-layout)/my/posts/page.tsx
  app/(main-layout)/my/profile/page.tsx
  app/(main-layout)/my/ticketbook/page.tsx
  app/(main-layout)/page.tsx
  app/(main-layout)/performance/page.tsx
  src/components/Common/ActionBar.tsx
  src/components/Common/Dropdown.tsx
  src/components/Common/EditDeleteButton.tsx
  src/components/Common/ListToolbar.tsx
  src/components/Common/LogoAnimation.tsx
  src/components/Common/NavigationBar.tsx
  src/components/Common/Sidebar.tsx
  src/components/Common/SidebarProfile.tsx
  src/components/Common/Textarea.tsx
  src/components/common/GenreButton.tsx
  src/components/common/Header.tsx
  src/components/modal/ModalContainer.tsx
  src/components/page/community/CommentEditForm.tsx
  src/components/page/community/CommentListItem.tsx
  src/components/page/community/CommentListToolbar.tsx
  src/components/page/community/CommentPostForm.tsx
  src/components/page/community/PostListItem.tsx
  src/components/page/community/PostListToolbar.tsx
  src/components/page/notification/NotificationHeader.tsx
  src/components/page/notification/NotificationListItem.tsx
  src/components/page/notification/NotificationListToolbar.tsx
  src/components/page/notification/NotificationPopup.tsx
  src/components/page/ticketbook/Rating.tsx
  src/components/page/ticketbook/TicketbookDetail.tsx
  src/icons/Icon.tsx
  src/lib/utils.ts
  src/utils/formatDate.ts
  src/utils/timeAgo.ts
Labels: refactor
